export const LOAD_LIST = "LOAD_LIST";
export const LOAD_LIST_PENDING = "LOAD_LIST_PENDING";
export const LOAD_LIST_FULFILLED = "LOAD_LIST_FULFILLED";
export const LOAD_LIST_REJECTED = "LOAD_LIST_REJECTED";
