export const LOAD_LIST = "LOAD_LIST";
export const LOAD_LIST_PENDING = "LOAD_LIST_PENDING";
export const LOAD_LIST_FULFILLED = "LOAD_LIST_FULFILLED";
export const LOAD_LIST_REJECTED = "LOAD_LIST_REJECTED";

export const LOAD_REDDIT = "LOAD_REDDIT";
export const LOAD_REDDIT_PENDING = "LOAD_REDDIT_PENDING";
export const LOAD_REDDIT_FULFILLED = "LOAD_REDDIT_FULFILLED";
export const LOAD_REDDIT_REJECTED = "LOAD_REDDIT_REJECTED";

export const DISMISS_REDDIT = "DISMISS_REDDIT";
